name: Ejemplo workflow1

on:
    push:
        branches: [main]
jobs:
    trabajo1:
        runs-on: ubuntu-latest
        steps:
          - name: 1. Descargar mi código
            uses: actions/checkout@v7

          - run: echo "Esta es una linea con variables $GITHUB_ACTOR 😊"

          - run: echo 'Repositorio de ${{github.repository}} 👌. El trabajo actual esta ${{job.status}}'

          - run: |
                 echo 'Este es el evento activado en el workflow ${{github.event_name}} '
                 echo 'en la ruta absoluta de ${{github.workspace}}. El runner tiene un SO ${{runner.os}} con una arquitectura ${{runner.arch}}'

          - name: Realizando setup de java
            uses: actions/setup-java@v6

          - run: echo 'VERSION_JAVA=$(java --version)' >> $GITHUB_ENV
          - run: echo "La version de java es $VERSION_JAVA"


          - name : Crear variables locales
            run: |
                MI_NOMBRE= "Samuel"
                echo "Hola $MI_NOMBRE"
            
          - name: Crear variables para variables de entorno de github
            run: | 
                 echo "USUARIO_LOGUEADO=Samuel" >> $GITHUB_ENV
                 echo "PUERTO_CUSTOM=8080" >> $GITHUB_ENV
          - name: Mostrar variables de entorno guardadas en github
            run: |
                 echo "El usuario logueado es $USUARIO_LOGUEADO"
                 echo "El puerto elegido es $PUERTO_CUSTOM"

          - name: Guardar version maven
            run: |
                 echo "VERSION_MAVEN=$(mvn --version)" >> $GITHUB_ENV

          - name: Mostrar version maven
            run: echo "$VERSION_MAVEN"
            
          


                 
            
